### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by oethanx** [fbef0102/L4D1-Competitive-Plugins#1]
You can add the hidden quick throw animation as one of the key combinations in "l4d_tank_attack_control" plugin. The quick throw is enabled with "tank_rock_overhead_percent 0"

**Comment by fbef0102** [comment]
what does the hidden quick throw animation looks like?

not one of animation below?
(MOUSE2) 1handed overhand
(E) underhand
(R) 2handed overhand

**Comment by oethanx** [comment]
Change this cvar tank_rock_overhead_percent 0 and then throw a rock as a tank in third-person view. It's a hidden animation from l4d beta I think

**Comment by oethanx** [comment]
https://www.youtube.com/watch?v=2gf-XLquP7Y&ab_channel=MattNF

**Comment by fbef0102** [comment]
no
