### ISSUE TITLE
l4d_tank_props

### ISSUE THREAD

**Issue by oethanx** [fbef0102/L4D1-Competitive-Plugins#2]
Tank props will not disappear even after the tank is dead

**Comment by fbef0102** [comment]
which object, do those Tank props glow ?

**Comment by oethanx** [comment]
Yes, props do stop glowing when the tank dies but they don't disappear

**Comment by fbef0102** [comment]
wired, I just tested and it totally works, can you make a screenshot?

**Comment by oethanx** [comment]
https://i.imgur.com/uabGEVK.jpeg 
https://i.imgur.com/ZWgBkuj.jpeg

Linux
SourceMod Version: 1.10.0.6499
Metamod:Source version 1.11.0-dev+1143
"L4D2 Tank Hittable Glow" (1.7) by Harry Potter

**Comment by fbef0102** [comment]
I'm glad someone use my plugin "L4D2 Tank Hittable Glow", but 

First, You post this issue on the wrong place
(This is "L4D1-Competitive-Plugins")

Second, you are using "L4D2 Tank Hittable Glow", I guess you download it from [[L4D/L4D2] Tank Hittable Prop Glow](https://forums.alliedmods.net/showthread.php?t=312447) or [Github](https://github.com/fbef0102/L4D2-Plugins/tree/master/l4d2_tank_props_glow).
I think I didn't make it clear, this plugin "L4D2 Tank Hittable Glow" **only adds a glow when a Tank punches a Hittable**
, it doesn't make tank props disappear...

Third, if you want to make them disappear in L4D2, use **[l4d_tank_props.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d_tank_props.sp)**
