### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Arnim0** [fbef0102/L4D1-Competitive-Plugins#3]
Hello if I have request  setup my server    
All I need 
**1v1 hunters 
2v2  hunters 
3v3 hunters 
4v4 hunters 
4v4 hardcore
4v4 pub
Hunter skeets practice** 
100 tickrate server of course 
 But on  **1v1 **hunters**** allow spawn **tank** and **witch**  each round not just Final 
And as well on all **others mods** 
Is that possible can do that and provide me **sp** **files** after done with it  i know have to **pay** you to **modify** that  
Is that possible ?

**Comment by fbef0102** [comment]
discord discuss
